# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - db
#     links:
#       - 'db:db'
#   db:
#     image: postgres:13.3
#     environment:
#       - POSTGRES_DB=TestingDocker
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=sa
#     ports:
#       - '5432:5432'
#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - '5050:80'
# version: '3.1'

services:
  db:
    image: postgres:13.0
    container_name: testing-docker
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: postgres
      POSTGRES_DB: TestingDocker
    restart: always
